# Generated by Django 4.0.6 on 2022-08-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='destination',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=35),
        ),
    ]
