# Generated by Django 4.0.6 on 2022-08-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_account_account_type_alter_account_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ID_number',
            new_name='id_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='employment_status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_wallet', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_wallet', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='Wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_wallet', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_transaction', to='wallet.transaction'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thirdparty_currency', to='wallet.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_customer', to='wallet.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='thirdparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_thirdparty', to='wallet.thirdparty'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_currency', to='wallet.currency'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_customer', to='wallet.customer'),
        ),
    ]
