# Generated by Django 4.0.6 on 2022-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rename_id_number_customer_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='origin_account',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
