# Generated by Django 4.0.6 on 2022-09-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_remove_transaction_thirdparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='origin_account',
            field=models.CharField(default='STRING', max_length=140),
        ),
    ]
